// Mocks generated by Mockito 5.4.6 from annotations
// in sentinel/test/integration/guest_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sentinel/models/guest.dart' as _i2;
import 'package:sentinel/providers/guest_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGuest_0 extends _i1.SmartFake implements _i2.Guest {
  _FakeGuest_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MockGuestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockGuestService extends _i1.Mock implements _i3.MockGuestService {
  MockMockGuestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Guest>> getTodayGuests() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayGuests, []),
            returnValue: _i4.Future<List<_i2.Guest>>.value(<_i2.Guest>[]),
          )
          as _i4.Future<List<_i2.Guest>>);

  @override
  _i4.Future<List<_i2.Guest>> getGuests({
    DateTime? startDate,
    DateTime? endDate,
    String? householdId,
    _i2.GuestStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGuests, [], {
              #startDate: startDate,
              #endDate: endDate,
              #householdId: householdId,
              #status: status,
            }),
            returnValue: _i4.Future<List<_i2.Guest>>.value(<_i2.Guest>[]),
          )
          as _i4.Future<List<_i2.Guest>>);

  @override
  _i4.Future<List<_i2.Guest>> searchGuests(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGuests, [query]),
            returnValue: _i4.Future<List<_i2.Guest>>.value(<_i2.Guest>[]),
          )
          as _i4.Future<List<_i2.Guest>>);

  @override
  _i4.Future<_i2.Guest> createGuest(_i2.Guest? guest) =>
      (super.noSuchMethod(
            Invocation.method(#createGuest, [guest]),
            returnValue: _i4.Future<_i2.Guest>.value(
              _FakeGuest_0(this, Invocation.method(#createGuest, [guest])),
            ),
          )
          as _i4.Future<_i2.Guest>);

  @override
  _i4.Future<_i2.Guest> updateGuest(_i2.Guest? guest) =>
      (super.noSuchMethod(
            Invocation.method(#updateGuest, [guest]),
            returnValue: _i4.Future<_i2.Guest>.value(
              _FakeGuest_0(this, Invocation.method(#updateGuest, [guest])),
            ),
          )
          as _i4.Future<_i2.Guest>);

  @override
  _i4.Future<void> deleteGuest(String? guestId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGuest, [guestId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
